const projects = [
  {
    id: 1,
    name: "RUGIR",
    rol: "Front end developer",
    date: "Jun 2024",
    detail: "Sitio web para marca de alfombras. Muestra la información relevante del comercio. Diseño responsive.",
    technologies: "Javascript · React · Css3",
    repository: "https://github.com/matidehoyos/rugirTailw",
    web: "https://rugirmdq.vercel.app/",
    img: 'ruggir.png',
    imgMov: 'rugirMov.png',
  },
  {
    id: 2,
    name: "ELECTROAUTO",
    rol: "Full stack developer",
    date: "Apr 2024",
    detail: "Aplicación web ecommerce. Con varias vistas, incluyendo tienda online, y panel autoadministrable. Diseño responsive.",
    technologies: "NodeJs · Express · PostgreSql · Sequelize · ReactJs · Redux · Css3 · Mercado Pago · Auth0",
    repository: "https://github.com/matidehoyos/Tienda-Electroauto",
    web: "https://electroauto.vercel.app/",
    img: 'electro.png',
    imgMov: 'ElectroMov.png',
  },
  {
    id: 3,
    name: "WEATHER APP",
    rol: "Full stack developer",
    date: "May 2024",
    detail: "Aplicación web del clima. Consume datos de API externa. Diseño responsive.",
    technologies: "Javascript · NodeJs · Express · ReactJs · Sass",
    repository: "https://github.com/matidehoyos/weatherapp",
    web: "https://climappmdh.vercel.app/",
    img: 'clima.png',
    imgMov: 'climaMov.png',
  },
  {
    id: 4,
    name: "WEDEVELOP",
    rol: "Full stack developer",
    date: "Feb 2024",
    detail: "Aplicación web autocotizadora. Reviews de clientes, proyectos, mailer, pasarellas de pagos. Diseño responsive.",
    technologies: "Javascript · NodeJs · Express · ReactJs · MongoDB",
    repository: "https://github.com/Freetzen/WeDevelop",
    web: "https://wedevelop.vercel.app/",
    img: 'wedev.png',
    imgMov: 'wedevv.jpeg',
  },
  {
    id: 5,
    name: "POKEMON APP",
    rol: "Full stack developer",
    date: "Jan 2024",
    detail: "Aplicación web que consume datos de API externa y los guarda en base de datos para luego listarlos a traves de filtros combinados. Diseño responsive.",
    technologies: "Javascript · NodeJs · Express · ReactJs · PostgreSql",
    repository: "https://github.com/matidehoyos/Pokemon-proyecto",
    web: "",
    img: 'poke.png',
    imgMov: 'pokeMov.png',
  },
  {
    id: 6,
    name: "PORTFOLIO",
    rol: "Full stack developer",
    date: "Abr 2024",
    detail: "Portfolio web responsive. Exhibición de proyectos.",
    technologies: "Javascript · ReactJs · CSS3",
    repository: "https://github.com/matidehoyos/portfolio",
    web: "https://matiasdehoyos.vercel.app/",
    img: 'portfolio.png',
    imgMov: 'portfolioMov.png',
  },
];

export default projects;
