const projects = [
  {
    id: 0,
    name: "MODO DIGITAL",
    rol: "Front end developer",
    date: "Aug 2024",
    detail: "Página web responsive, mobile first. Tipo institucional, muestra la información relevante de la institución y su producto.",
    technologies: "ReactJs · Tailwind · Html5 · Vercel · Visual studio",
    repository: "https://github.com/matidehoyos/modo",
    web: "https://mododigital.vercel.app/",
    img: 'modo.jpeg',
    imgP: 'modod.png',
  },
  {
    id: 1,
    name: "RUGIR",
    rol: "Front end developer",
    date: "Jun 2024",
    detail: "Sitio web para marca de alfombras. Muestra la información relevante del comercio. Diseño responsive. Mobile first.",
    technologies: "Javascript · React · Css3",
    repository: "https://github.com/matidehoyos/rugirTailw",
    web: "https://rugirmdq.vercel.app/",
    img: 'RUGIR.jpeg',
    imgP: 'rug.png',
  },
  {
    id: 2,
    name: "ELECTROAUTO",
    rol: "Full stack developer",
    date: "Apr 2024",
    detail: "Aplicación web ecommerce. Con varias vistas, incluyendo tienda online, y panel autoadministrable. Diseño responsive.",
    technologies: "NodeJs · Express · PostgreSql · Sequelize · ReactJs · Redux · Css3 · Mercado Pago · Auth0",
    repository: "https://github.com/matidehoyos/Tienda-Electroauto",
    web: "https://electroauto.vercel.app/",
    img: 'ele.jpeg',
    imgP: 'e.png',
  },
  {
    id: 3,
    name: "POKEMON APP",
    rol: "Full stack developer",
    date: "Jan 2024",
    detail: "Aplicación web que consume datos de API externa y los guarda en base de datos para luego listarlos a traves de filtros combinados. Diseño responsive.",
    technologies: "Javascript · NodeJs · Express · ReactJs · Redux · PostgreSql",
    repository: "https://github.com/matidehoyos/Pokemon-proyecto",
    web: "https://pokemonmdh.vercel.app/",
    img: 'poke.png',
  },
  {
    id: 4,
    name: "Rick&Morty",
    rol: "Full stack developer",
    date: "Nov 2023",
    detail: "App web sobre Rick & Morty. Consume datos de Api externa, los filtra y muestra segun gustos del usuario.",
    technologies: "Javascript · NodeJs · ReactJs · CSS3",
    repository: "https://github.com/matidehoyos/RickyMorty",
    web: "https://rickymortymdh.vercel.app/",
    img: 'rm.png',
  },
  {
    id: 5,
    name: "WEATHER APP",
    rol: "Full stack developer",
    date: "May 2024",
    detail: "Aplicación web del clima. Consume datos de API externa. Diseño responsive.",
    technologies: "Javascript · NodeJs · Express · ReactJs · Sass",
    repository: "https://github.com/matidehoyos/weatherapp",
    web: "https://climappmdh.vercel.app/",
    img: 'c.png',
  },
  {
    id: 6,
    name: "PORTFOLIO",
    rol: "Full stack developer",
    date: "Abr 2024",
    detail: "Portfolio web responsive. Exhibición de proyectos.",
    technologies: "Javascript · ReactJs · CSS3",
    repository: "https://github.com/matidehoyos/portfolio",
    web: "https://matiasdehoyos.vercel.app/",
    img: 'p.png',
  },
  {
    id: 7,
    name: "WEDEVELOP",
    rol: "Full stack developer",
    date: "Feb 2024",
    detail: "Aplicación web autocotizadora. Reviews de clientes, proyectos, mailer, pasarellas de pagos. Diseño responsive.",
    technologies: "Javascript · NodeJs · Express · ReactJs · MongoDB",
    repository: "https://github.com/Freetzen/WeDevelop",
    web: "https://github.com/Freetzen/WeDevelop",
    img: 'wedev.png',
  },
];

export default projects;
